/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../components/layouts/aside.vue')['default']
    Header: typeof import('./../components/layouts/header.vue')['default']
    ImageIcon: typeof import('./../components/common/ImageIcon.vue')['default']
    LayButton: typeof import('@layui/layui-vue')['LayButton']
    LayButtonGroup: typeof import('@layui/layui-vue')['LayButtonGroup']
    LayConfigProvider: typeof import('@layui/layui-vue')['LayConfigProvider']
    LayDropdown: typeof import('@layui/layui-vue')['LayDropdown']
    LayDropdownMenu: typeof import('@layui/layui-vue')['LayDropdownMenu']
    LayDropdownMenuItem: typeof import('@layui/layui-vue')['LayDropdownMenuItem']
    LayForm: typeof import('@layui/layui-vue')['LayForm']
    LayFormItem: typeof import('@layui/layui-vue')['LayFormItem']
    LayIcon: typeof import('@layui/icons-vue')['LayIcon']
    LayLayRadioGroup: typeof import('@layui/layui-vue')['LayLayRadioGroup']
    LayRadio: typeof import('@layui/layui-vue')['LayRadio']
    LayRadioGroup: typeof import('@layui/layui-vue')['LayRadioGroup']
    LayRipple: typeof import('@layui/layui-vue')['LayRipple']
    LaySelect: typeof import('@layui/layui-vue')['LaySelect']
    LaySelectOption: typeof import('@layui/layui-vue')['LaySelectOption']
    LaySpace: typeof import('@layui/layui-vue')['LaySpace']
    LaySwitch: typeof import('@layui/layui-vue')['LaySwitch']
    LayTable: typeof import('@layui/layui-vue')['LayTable']
    LayTag: typeof import('@layui/layui-vue')['LayTag']
    LayTooltip: typeof import('@layui/layui-vue')['LayTooltip']
    RippleButton: typeof import('./../components/common/RippleButton.vue')['default']
    RiveLoading: typeof import('./../components/common/RiveLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/common/SvgIcon.vue')['default']
  }
}
