/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../components/layouts/aside.vue')['default']
    Header: typeof import('./../components/layouts/header.vue')['default']
    ImageIcon: typeof import('./../components/common/ImageIcon.vue')['default']
    RippleButton: typeof import('./../components/common/RippleButton.vue')['default']
    RiveLoading: typeof import('./../components/common/RiveLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/common/SvgIcon.vue')['default']
    SwitchTheme: typeof import('./../components/common/SwitchTheme.vue')['default']
  }
}
